// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RightWindow1Search: typeof import('./src/components/RightWindow1Search.vue')['default']
    ToolsBar: typeof import('./src/components/ToolsBar.vue')['default']
    WhiteBox: typeof import('./src/components/whiteBox/index.vue')['default']
  }
}
